[tool.poetry]
name = "ypres"
version = "0.3.3"
description = ""
authors = ["Andrew Hankinson <andrew.hankinson@gmail.com>"]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
mypy = "^0.991"
flake8 = "^2.4.0"
mccabe = "^0.3"
pep8 = "^1.5.7"
py = "1.4.26"
pyflakes = "^0.8.1"
tox = "^1.9.2"
wheel = "^0.24.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
