[tool.poetry]
name = "ypres"
version = "0.3.3"
description = ""
authors = ["Andrew Hankinson <andrew.hankinson@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.group.dev.dependencies]
pep8 = "^1.5.7"
py = "1.4.26"
flake8 = "^6.0.0"
pyflakes = "^3.0.1"
wheel = "^0.40.0"
mypy = "^1.2.0"
ipython = "^8.13.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
