name: Check formatting and imports
on:
  - push
  - pull_request
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
      - name: Install requirements
        run: poetry install
      - name: Run black
        run: poetry run black --check --diff ypres tests
      - name: Run mypy
        run: poetry run mypy ypres tests
      - name: Run flake8
        run: poetry run flake8 ypres tests
      - name: Run unit tests
        run: python -m unittest tests/*.py